// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Quit():Promise<void>;

export function SetAlwaysOnTop(arg1:boolean):Promise<void>;

export function SetWindowTransparent(arg1:boolean):Promise<void>;
