// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function SetWindowTransparent(arg1) {
  return window['go']['main']['App']['SetWindowTransparent'](arg1);
}
